var webObjects = [{ title: "Good Sales Email", text: "A collection of sales emails by various different companies", link: "http://goodsalesemails.com/" },
{ title: "Playbook", text: "Tips on career development and design process", link: "https://askplaybook.com/" },
{ title: "Bestfolios", text: "UI/UX designer portfolios and more", link: "https://www.bestfolios.com/" },
{ title: "If You Could Jobs", text: "The place to find and post creative jobs", link: "https://www.ifyoucouldjobs.com/" },
{ title: "Boooom", text: "Design management and leadership jobs", link: "https://boooom.co/" },
{ title: "Dribbble jobs", text: "Connect with designers and jobs worldwide", link: "https://dribbble.com/jobs" },
{ title: "Designer News Jobs", text: "Jobs for designers and developers", link: "https://www.designernews.co/jobs/" },
{ title: "Design Jobs Board", text: "The best design jobs today", link: "https://www.designjobsboard.com/" },
{ title: "Epic Jobs", text: "Discover jobs for design", link: "https://epicjobs.co/" },
{ title: "We The Makers Club", text: "Sources and selects the top creative jobs", link: "http://wethemakers.club/" },
{ title: "Amazing Design People", text: "Find amazing designers for hire", link: "https://www.adplist.org/" },
{ title: "How Much Should I Charge?", text: "A calculator for design work pricing", link: "https://thenuschool.com/how-much/#/projects" },
{ title: "Checklist Design", text: "A collection of scope focused design checklists", link: "https://www.checklist.design/" },
{ title: "Web Design Client Questionnaire", text: "A list of questions to ask your client", link: "https://business.tutsplus.com/articles/how-to-extract-the-facts-with-a-web-design-client-questionnaire--fsw-1830" },
{ title: "Front End Checklist", text: "Checklist for modern websites and meticulous developers", link: "https://frontendchecklist.io/" },
{ title: "Website checklist", text: "A list of task necessary for website desing and development", link: "http://www.skyrme.com/tools/webplan.htm" },
{ title: "UX Project Checklist", text: "A list of important UX topics to address", link: "https://uxchecklist.github.io/" },
{ title: "Design checklist", text: "A list of things the client should provide their designer", link: "https://traceygrady.com/2015/08/09/design-checklist-what-clients-should-provide-their-designer/" },
{ title: "Reading Forms", text: "Pictures of graphic design focused art exhibitions", link: "https://readingforms.com/" },
{ title: "Dada & Surrealism", text: "A collection of Dada art pieces", link: "https://dada.lib.uiowa.edu/" },
{ title: "Archives.design", text: "A digital archive of graphic design related items", link: "https://archives.design/" },
{ title: "Pattern Collect", text: "A curated gallery of patterns by awesome designers and illustrators", link: "https://patterncollect.com/" },
{ title: "Color Inspiration: Sunsets", text: "Some cool gradients courtesy of mother nature", link: "https://digitalsynopsis.com/design/sunrise-sunset-photos-sky-series-eric-cahan/" },
{ title: "70s/early 80s Japanese Design", text: "A collection of old school Japanese design", link: "https://www.are.na/josef-minor/70s-early-80s-japanese-design" },
{ title: "Gradients daily", text: "A series of unique daily gradients", link: "https://gradientsdaily.com/Homepage" },
{ title: "Pinterest", text: "A popular moodboarding network", link: "https://www.pinterest.com/" },
{ title: "Muzli", text: "All the design inspiration you need. Served fresh.", link: "https://muz.li/" },
{ title: "Designspiration", text: "Moodboarding for designers", link: "https://www.designspiration.com/" },
{ title: "Fonts in Use", text: "A searchable archive of typographic design", link: "https://fontsinuse.com/" },
{ title: "Beautiful Web Type", text: "Check out a curated collection of the most beautiful webfonts", link: "https://hellohappy.org/beautiful-web-type/" },
{ title: "Dribble", text: "Online community for showcasing user artwork", link: "https://dribbble.com/" },
{ title: "Follow and learn from talented designers", text: "Find inspiration from other designers", link: "https://www.designerhunt.io/" },
{ title: "Behance", text: "Find inspiration from other designers", link: "https://www.behance.net/" },
{ title: "Design Systems Repo", text: "A frequently updated collection of Design System examples", link: "https://designsystemsrepo.com/" },
{ title: "Adele", text: "Repository of publicly available design systems", link: "https://adele.uxpin.com/" },
{ title: "Identity Designed", text: "A compilation of visual identities from design studios all over the world", link: "https://identitydesigned.com/" },
{ title: "Findguidelin.es", text: "The fastest way to find brand assets for companies", link: "http://www.findguidelin.es/" },
{ title: "Carbon Design System", text: "IBM's design system", link: "https://www.carbondesignsystem.com/" },
{ title: "Spectrum by Adobe", text: "Adobe's design system", link: "https://spectrum.adobe.com/" },
{ title: "Polaris", text: "Shopify's design system", link: "https://polaris.shopify.com/" },
{ title: "Marvel Styleguide", text: "An inventory of UI components, design patterns and brand assets", link: "https://marvelapp.com/styleguide/overview/introduction" },
{ title: "Zendesk Garden", text: "User interface components for Zendesk products", link: "https://garden.zendesk.com/" },
{ title: "Github Primer", text: "The design system that powers GitHub", link: "https://primer.style/" },
{ title: "FutureLearn", text: "Design system for FutureLearn", link: "https://storybook.futurelearn.com/" },
{ title: "Atlassian Design", text: "Atlassian's design system", link: "https://atlassian.design/" },
{ title: "Mixpanel", text: "Mixpanel Design System for design and development", link: "https://design.mixpanel.com/" },
{ title: "Album Colors", text: "A collection of album covers organized by color", link: "https://albumcolors.com/" },
{ title: "Typo/graphic", text: "Connect to different cultures through poster design", link: "https://www.typographicposters.com/" },
{ title: "Film Art Gallery", text: "A collection of vintage movie posters", link: "https://filmartgallery.com/" },
{ title: "Screenlane", text: "The best UI inspiration, every day", link: "https://screenlane.com/" },
{ title: "Siteinspire", text: "Showcase of finest web and interactive design ", link: "https://www.siteinspire.com/" },
{ title: "Siiimple", text: "A network of minimalistic websites", link: "https://siiimple.com/" },
{ title: "Httpster", text: "A curated collection of nice looking websites", link: "https://httpster.net/" },
{ title: "Awwwards", text: "Awards for design, creativity and innovation on web", link: "https://www.awwwards.com/" },
{ title: "Best Website Gallery", text: "Hand-picked website inspiration", link: "https://bestwebsite.gallery/" },
{ title: "One Page Love", text: "One page websites, templates and resources", link: "https://onepagelove.com/" },
{ title: "UI Jar", text: "Design inspiration for your projects", link: "https://uijar.com/" },
{ title: "Lapa Ninja", text: "Landing page design inspiration from around the web", link: "https://www.lapa.ninja/" },
{ title: "H69", text: "Currated list of landing page examples from around the web", link: "https://www.h69.design/" },
{ title: "Land Book", text: "Websites to help find inspiration and motivation", link: "https://land-book.com/" },
{ title: "Dark Mode Design", text: "Showcasing the most beautifully designed dark mode websites", link: "https://www.darkmodedesign.com/" },
{ title: "Ecomm.design", text: "eCommerce website design gallery", link: "https://ecomm.design/" },
{ title: "Minimal Gallery", text: "Daily curated, hand-picked collection of minimal web design inspiration", link: "https://minimal.gallery/" },
{ title: "User Inyerface", text: "A worst-practice UI experiment", link: "https://userinyerface.com/" },
{ title: "The Useless Web", text: "A collection of random, yet intriguing websites", link: "https://theuselessweb.com/" },
{ title: "Stumbled", text: "A collection of random, yet useful websites", link: "https://stumbled.cc/" },
{ title: "Mobbin", text: "Latest mobile design patterns", link: "https://mobbin.design/" },
{ title: "UI Sources", text: "Interactions from the best designed and top grossing apps", link: "https://www.uisources.com/" },
{ title: "Into the Dark", text: "Explore color palettes, contrast, and legibility in a dark theme", link: "https://design.google/library/material-design-dark-theme/" },
{ title: "Nicely done", text: "Products and pattern designs inspiration", link: "https://nicelydone.club/" },
{ title: "Collect UI", text: "Daily inspiration collected from daily UI archive and beyond", link: "https://collectui.com/" },
{ title: "iOS icon Gallery", text: "Showcasing beautiful icon designs from iOS", link: "https://www.iosicongallery.com/" },
{ title: "Design Vault", text: "UI patterns and design inspiration from real products", link: "https://designvault.io/" },
{ title: "Pttrns", text: "Design patterns, resources and inspiration", link: "https://www.pttrns.com/" },
{ title: "UserOnBoard", text: "Source for user onboarding teardowns", link: "https://www.useronboard.com/user-onboarding-teardowns/" },
{ title: "Really Good UX", text: "Screenshots and examples of great UX from products", link: "https://www.reallygoodux.io/" },
{ title: "Scrnshts", text: "Curated collection of app store screenshots", link: "https://scrnshts.club/" },
{ title: "Really Good Emails", text: "Curated collection of noteworthy email designs", link: "https://reallygoodemails.com/" },
{ title: "WindowSwap", text: "A collection of window views from around the world", link: "https://www.window-swap.com/" },
{ title: "Design Kit", text: "A collection of desing thinking methodes", link: "https://www.designkit.org/methods" },
{ title: "Google Sprints", text: "Open-source resource for designs leaders and product owners", link: "https://designsprintkit.withgoogle.com/" },
{ title: "Guide to UXR", text: "A curated collection of 250+ resources and tools dedicated to user research", link: "http://guidetouxr.com/" },
{ title: "User Centered Design Canvas", text: "New ux tool combining user needs with business goals", link: "https://ucdc.therectangles.com/" },
{ title: "A Lightweight Branding Exercise for Startups", text: "A bottom-up, alignment-oriented approach", link: "https://bbergher.medium.com/a-lightweight-branding-exercise-for-startups-8776f0cb0ea7" },
{ title: "18F Methods", text: "A collection of tools to bring human-centered design into your project", link: "https://methods.18f.gov/" },
{ title: "The Design Sprints", text: "A design spring layout by GV", link: "https://www.gv.com/sprint/" },
{ title: "Enterprise Design Sprints", text: "A design spring layout by InVision", link: "https://www.designbetter.co/enterprise-design-sprints" },
{ title: "Remote Design Sprint", text: "A remote design sprint layout by Wayfair", link: "https://medium.com/wayfair-design/our-remote-design-sprint-a-step-by-step-toolkit-b09e6712d5ed" },
{ title: "Product Design Sprint", text: "A design spring layout by Mozilla", link: "https://toolkit.mozilla.org/method/product-design-sprint/" },
{ title: "Design-sprint", text: "A design spring layout by Thoughtbot", link: "https://github.com/thoughtbot/design-sprint" },
{ title: "Brand Archetypes", text: "A list of 36 brand archetypes", link: "https://iconicfox.com.au/brand-archetypes/" },
{ title: "Untools", text: "A collection of thinking tools and frameworks", link: "https://untools.co/" },
{ title: "Sneakpeekit", text: "Printable grids for design wireframing", link: "https://sneakpeekit.com/" },
{ title: "Sketchsheets", text: "Ready to print sheets themplates for UX designers", link: "https://sketchsheets.com/" },
{ title: "Gridzzly", text: "Make your own grid paper", link: "http://gridzzly.com/" },
{ title: "Sketchize", text: "A free wireframing kit that contains a set of printable device sketch sheets", link: "https://www.sketchize.com/" },
{ title: "Form", text: "A free wireframe kit from InVision", link: "https://www.invisionapp.com/inside-design/design-resources/free-wireframe-kit-form/" },
{ title: "SessionLab", text: "Workshop planning tool", link: "https://www.sessionlab.com/" },
{ title: "Miro", text: "Collaborative whiteboard", link: "https://miro.com/" },
{ title: "Cnvs", text: "Canvas models generator", link: "https://cnvs.online/en/w/-M_zZX0r1bys2lNkplEL" },
{ title: "Evolt", text: "User card generator", link: "https://evolt.io/" },
{ title: "Make My Persona", text: "Fast and easy persona builder", link: "https://www.hubspot.com/make-my-persona" },
{ title: "Collabshot", text: "Quick and easy collaborative feedback tool", link: "https://www.collabshot.com/" },
{ title: "Milanote", text: "Whiteboard with emphasis on organization", link: "https://milanote.com/" },
{ title: "Are.na", text: "Whiteboard tool for moodboards", link: "https://www.are.na/" },
{ title: "Pixel Surplus Fonts", text: "Free modern typefaces", link: "https://pixelsurplus.com/collections/free-fonts" },
{ title: "Fontain", text: "A selection of open source fonts together with their source files", link: "https://www.fontain.org/" },
{ title: "Font Arena", text: "Free fonts and alternatives to premium fonts", link: "https://fontsarena.com/" },
{ title: "Free Script Fonts", text: "Free versions of latest script fonts", link: "https://www.freescriptfonts.net/" },
{ title: "Befonts", text: "Best free fonts for personal and commercial use", link: "https://befonts.com/" },
{ title: "Pinspiry", text: "Collection of free fonts for every design project", link: "https://pinspiry.com/category/free-resources/fonts/" },
{ title: "Lost Type", text: "Gorgeous pay-what-you-can fonts", link: "http://www.losttype.com/" },
{ title: "Font Library", text: "Free typefaces", link: "https://fontlibrary.org/" },
{ title: "Font Squirrel", text: "High quality, legitimately free fonts", link: "https://www.fontsquirrel.com/" },
{ title: "Google Fonts", text: "Making the web more beautiful, fast, and open through great typography", link: "https://fonts.google.com/" },
{ title: "78 best free fonts", text: "The non-obvious free to use choices", link: "https://www.creativebloq.com/graphic-design-tips/best-free-fonts-for-designers-1233380" },
{ title: "Online Web Fonts", text: "Free web fonts", link: "https://www.onlinewebfonts.com/top" },
{ title: "Future fonts", text: "Where type designers sell fonts in progress", link: "https://www.futurefonts.xyz/typefaces" },
{ title: "Adobe Fonts", text: "Features the world's leading type foundries with lots of beautiful fonts", link: "https://fonts.adobe.com/" },
{ title: "MyFonts", text: "The world's largest collection of fonts for print, products and screens", link: "https://www.myfonts.com/" },
{ title: "Font Shop", text: "A font store with multiple famous and affordable typefaces", link: "https://www.fontshop.com/" },
{ title: "Fontstand", text: "Test and use high-quality fonts on all platforms", link: "https://fontstand.com/" },
{ title: "Velvetyne", text: "Free and open source type foundry", link: "https://www.velvetyne.fr/" },
{ title: "Open Foundry", text: "Curated open-source fonts", link: "https://open-foundry.com/" },
{ title: "Pangram Pangram", text: "Free to try trend-conscious fonts", link: "https://pangrampangram.com/" },
{ title: "Optimo", text: "undefined", link: "https://optimo.ch/" },
{ title: "Swiss Typefaces", text: "undefined", link: "https://www.swisstypefaces.com/" },
{ title: "Sharp Type", text: "undefined", link: "https://sharptype.co/" },
{ title: "Bruta Types", text: "undefined", link: "http://brutatypes.com/" },
{ title: "Fatype", text: "undefined", link: "https://fatype.com/" },
{ title: "Schick Toikka", text: "undefined", link: "https://www.schick-toikka.com/" },
{ title: "Paratype", text: "undefined", link: "https://www.paratype.com/" },
{ title: "General Type Studio", text: "undefined", link: "https://www.generaltypestudio.com/" },
{ title: "Studio René Bieder", text: "undefined", link: "https://www.renebieder.com/" },
{ title: "Letters from Sweden", text: "undefined", link: "https://lettersfromsweden.se/" },
{ title: "Village", text: "undefined", link: "https://vllg.com/" },
{ title: "Dalton Maag", text: "undefined", link: "https://www.daltonmaag.com/" },
{ title: "Commercial Type", text: "undefined", link: "https://commercialtype.com/" },
{ title: "Process Type", text: "undefined", link: "https://processtypefoundry.com/" },
{ title: "DSType Foundry", text: "undefined", link: "https://www.dstype.com/" },
{ title: "A2-TYPE", text: "undefined", link: "https://www.a2-type.co.uk/" },
{ title: "Darden studio", text: "undefined", link: "https://www.dardenstudio.com/" },
{ title: "Just Another Foundry", text: "undefined", link: "https://justanotherfoundry.com/" },
{ title: "Klim Type Foundry", text: "undefined", link: "https://klim.co.nz/" },
{ title: "Grilli Type", text: "undefined", link: "https://www.grillitype.com/" },
{ title: "Milieu Grotesque", text: "undefined", link: "https://www.milieugrotesque.com/" },
{ title: "Lineto", text: "undefined", link: "https://lineto.com/#lineto-1-0" },
{ title: "Type together", text: "undefined", link: "https://www.type-together.com/font-catalogue" },
{ title: "Colophon Foundry", text: "undefined", link: "https://www.colophon-foundry.org/" },
{ title: "Dinamo", text: "undefined", link: "https://abcdinamo.com/" },
{ title: "ECAL", text: "undefined", link: "https://ecal-typefaces.ch/" },
{ title: "Font Fabric", text: "undefined", link: "https://www.fontfabric.com/" },
{ title: "Type Foundry Index", text: "A showcase of type foundries and designers", link: "https://type.lol/" },
{ title: "Typecache", text: "A comprehensive list of type foundries", link: "http://typecache.com/" },
{ title: "What Font Is", text: "Find any font from any image", link: "https://www.whatfontis.com/" },
{ title: "Fontjoy Pairing", text: "Font pairing tool", link: "https://fontjoy.com/" },
{ title: "Archetype", text: "Tool for creating consistent typography styles across projects", link: "https://archetypeapp.com/" },
{ title: "Typewolf", text: "Helps in picking the perfect font combination for your next project", link: "https://www.typewolf.com/" },
{ title: "Wordmark", text: "Previews text with fonts on your computer", link: "https://wordmark.it/" },
{ title: "Font Spark", text: "Quickly discover the best fonts for your next design project", link: "https://fontspark.app/" },
{ title: "Fontpair", text: "Helps your pair Google Fonts together to create beutiful font combinations", link: "https://www.fontpair.co/" },
{ title: "FontBase", text: "Free, beautiful and fast font manager", link: "https://fontba.se/" },
{ title: "Font Ninja", text: "A free browser extension that lets you inspect any fonts on any website", link: "https://www.fonts.ninja/" },
{ title: "Fontjoy Projector", text: "A neural network of font similarities", link: "https://fontjoy.com/projector/" },
{ title: "Fontifier", text: "Create a font from your handwriting", link: "http://www.fontifier.com/" },
{ title: "FontPrep", text: "Web Font generator for Mac", link: "http://thezinx.com/design/generate-web-font-mac-fontprep/" },
{ title: "Metaflop Modulator", text: "Create a typeface through modulation", link: "https://www.metaflop.com/modulator" },
{ title: "TransType 4", text: "Font format converter", link: "https://www.fontlab.com/font-converter/transtype/" },
{ title: "Typography Guru", text: "A large online font community", link: "https://typography.guru/" },
{ title: "Happy Hues", text: "Curated colors in context", link: "https://www.happyhues.co/" },
{ title: "Duo", text: "Collection of color combinations curated from the web", link: "https://duo.alexpate.uk/" },
{ title: "Palette App", text: "Build, analyze and edit smooth color palettes", link: "https://palettte.app/" },
{ title: "Colorbox", text: "Build accessible UI colour systems that scale", link: "https://colorbox.io/" },
{ title: "Palette Creato", text: "Google Chrome extension that creates a color palette from any image", link: "https://chrome.google.com/webstore/detail/palette-creator/iofmialeiddolmdlkbheakaefefkjokp" },
{ title: "Khroma", text: "Uses AI to learn which colors you like and creates pallets", link: "http://khroma.co/" },
{ title: "ColorSpace", text: "Generate color palettes and schemes from yout favorite color", link: "https://mycolor.space/" },
{ title: "Color Hunt", text: "Free and open platform for color inspiration", link: "https://colorhunt.co/" },
{ title: "Colorinspo", text: "All in one resource for finding colors", link: "https://colorsinspo.com/" },
{ title: "Adobe color", text: "Browse thousands of color combinations", link: "https://color.adobe.com/explore" },
{ title: "Sip", text: "Mac app to collect, organize and share your colors", link: "https://sipapp.io/" },
{ title: "Coolors", text: "Fast color scheme generator", link: "https://coolors.co/generate" },
{ title: "Eva Color Generator", text: "Complimentary color generator powered by deep learning", link: "https://colors.eva.design/" },
{ title: "Color Claim", text: "Collection of unique color for your future projects", link: "https://vanschneider.com/colors" },
{ title: "Pigment", text: "A unique way to generate fresh and vibrant colors", link: "https://pigment.shapefactory.co/" },
{ title: "BrandColors", text: "Biggest collection of official brand color codes", link: "https://brandcolors.net/" },
{ title: "LOL Colors", text: "Curated color palette for inspiration", link: "https://www.webdesignrankings.com/resources/lolcolors/" },
{ title: "ColorSpark", text: "A simple tool that generates random colors and gradients", link: "https://colorspark.app/" },
{ title: "Culrs", text: "Thoughtfully crafted and easy-to-use color palettes", link: "https://www.culrs.com/" },
{ title: "Paletton", text: "Color scheme generator", link: "https://paletton.com/" },
{ title: "0to255", text: "Color randomizer with tint selection", link: "https://www.0to255.com/" },
{ title: "Mesh Gradient", text: "Create beautiful mesh gradients with code export", link: "https://meshgradient.com/" },
{ title: "Mesher", text: "Gradient mash generator with CSS export", link: "https://www.csshero.org/mesher/" },
{ title: "Grabient", text: "Beautiful and simple UI for generating web gradients", link: "https://www.grabient.com/" },
{ title: "Blend", text: "A simple generator that blends two color together", link: "http://www.colinkeany.com/blend/" },
{ title: "Gradient Generator", text: "Gradient generator with improved transitions", link: "https://learnui.design/tools/gradient-generator.html" },
{ title: "LS Freebies", text: "100 mesh gradients in most popular formats", link: "https://products.ls.graphics/mesh-gradients/" },
{ title: "UI gradients", text: "Gallery of colour gradients for designers and developers", link: "https://uigradients.com/" },
{ title: "Gradient Hunt", text: "Thousands of curated colour gradients in a daily upadated collection", link: "https://gradienthunt.com/" },
{ title: "WebGradients", text: "Gradient collection", link: "https://webgradients.com/" },
{ title: "Nucleo", text: "Mac/Windows app to organize, customize and export all your icons", link: "https://nucleoapp.com/" },
{ title: "Icon Jar", text: "Icon organizer for macOS", link: "https://geticonjar.com/" },
{ title: "Noun Project", text: "Over 2 Million curated icons, created by a global community", link: "https://thenounproject.com/" },
{ title: "We Love Icon Fonts", text: "Collection of icon fonts", link: "https://weloveiconfonts.com/" },
{ title: "Feather", text: "Simply beautiful open source icons", link: "https://feathericons.com/" },
{ title: "Simple Icons", text: "Free SVG icons for popular brands", link: "https://simpleicons.org/" },
{ title: "Iconscout", text: "High-quality icons, illustration and stock photos", link: "https://iconscout.com/" },
{ title: "UseAnimations", text: "Animated icons with immediate implementation to your apps or websites", link: "https://useanimations.com/" },
{ title: "Flaticon", text: "Free to use icons", link: "https://www.flaticon.com/" },
{ title: "Icons8", text: "171.900 free icons", link: "https://icons8.com/icons" },
{ title: "Remix", text: "Open-source neutral-style system symbols", link: "https://remixicon.com/" },
{ title: "Eva", text: "480 delightful icons available for free", link: "https://akveo.github.io/eva-icons/" },
{ title: "Material Icons", text: "Delightful, beautifully crafted symbols for common actions and items", link: "https://fonts.google.com/icons" },
{ title: "Fontisto", text: "616+ scalable icons that can be instantly customized", link: "https://www.fontisto.com/icons" },
{ title: "Font Awesome", text: "The web's most popular icon set and toolkit", link: "https://fontawesome.com/" },
{ title: "CSS.gg", text: "Open-source CSS, SVG and Figma UI Icons", link: "https://css.gg/" },
{ title: "Boxicons", text: "Carefully crafted and simple vector icon set", link: "https://boxicons.com/" },
{ title: "Ikonate", text: "Fully customisable and accessible vector icons", link: "https://ikonate.com/" },
{ title: "Shape.so", text: "Customizable, animated icons and illustrations exportable to code", link: "https://shape.so/" },
{ title: "Iconset", text: "Free, croess-platform SVG icon manager", link: "https://iconset.io/" },
{ title: "Heroicons", text: "Open source icons from the creators of Tailwind CSS", link: "https://heroicons.dev/" },
{ title: "Iconoir", text: "A collection of 914 SVG icons", link: "https://iconoir.com/" },
{ title: "Line Icons", text: "2000+ handcrafted line icons for modern user interfaces", link: "https://lineicons.com/" },
{ title: "ICONSVG", text: "Quick customizable icons for your projects", link: "https://iconsvg.xyz/" },
{ title: "Polaris Icons", text: "A collection of simple and informative icons from Shopify's system", link: "https://polaris-icons.shopify.com/" },
{ title: "Evericons", text: "Collection of 460+ well-crafted icons", link: "http://www.evericons.com/" },
{ title: "Iconfinder", text: "Marketpalce for icons", link: "https://www.iconfinder.com/" },
{ title: "Streamline", text: "Over 30.000 something icons", link: "https://streamlinehq.com/" },
{ title: "Unsplash", text: "Free to use images and pictures", link: "https://unsplash.com/" },
{ title: "Burst", text: "Free to use photos", link: "https://burst.shopify.com/" },
{ title: "Death to Stock", text: "Free to use photos by artists", link: "https://deathtothestockphoto.com/join/" },
{ title: "ShotStash", text: "Independently managed free stock photo site", link: "https://shotstash.com/" },
{ title: "Cupcake", text: "Free, high-res photos by Jonas Nilsson Lee", link: "https://cupcake.nilssonlee.se/" },
{ title: "Gratisography", text: "Free to use photos", link: "https://gratisography.com/" },
{ title: "Getrefe", text: "Free to use photos", link: "https://getrefe.tumblr.com/" },
{ title: "IM Free", text: "Free to use images and pictures", link: "http://imcreator.com/free" },
{ title: "Jaymantri", text: "Free to use photos by a professional photographer", link: "https://jaymantri.com/" },
{ title: "Public Domain Archive", text: "Free to use photos", link: "https://publicdomainarchive.com/" },
{ title: "Magdeleine", text: "Handpicked free photos", link: "https://magdeleine.co/" },
{ title: "Picography", text: "Free to use photos", link: "https://picography.co/" },
{ title: "Creative Commons", text: "Free to use images and pictures", link: "https://search.creativecommons.org/" },
{ title: "Img.modem", text: "Free to use images", link: "http://img.modem.studio/" },
{ title: "Mixkit- Free assets for your next video project", text: "undefined", link: "https://mixkit.co/" },
{ title: "Coverr", text: "Download royalty free video stock footage", link: "https://coverr.co/" },
{ title: "Life of Vids", text: "Free videos, clips and loops", link: "https://www.lifeofvids.com/all/" },
{ title: "Motion Places", text: "Free video stock footage from around the world", link: "https://www.motionplaces.com/" },
{ title: "Vyoo", text: "Beautiful, free vertical videos", link: "https://www.veed.io/vyoo/" },
{ title: "Videezy", text: "Free stock videos shared by a community of videographers", link: "https://www.videezy.com/browse" },
{ title: "ISO Repuplic", text: "Free to use videos", link: "https://isorepublic.com/videos/" },
{ title: "Dissolve", text: "Premium videos", link: "https://dissolve.com/footage" },
{ title: "New Old Stock", text: "Free vintage photos", link: "https://nos.twnsnd.co/" },
{ title: "Foodies Feed", text: "Free food pictures", link: "https://www.foodiesfeed.com/" },
{ title: "Bucketlistly", text: "A wide array of free travel photos", link: "https://www.bucketlistly.blog/photos" },
{ title: "LandingStock", text: "A collection of free images for landing pages", link: "https://landingstock.com/" },
{ title: "Library Of Congress Images", text: "Free to use images from the library of congress", link: "https://www.loc.gov/free-to-use/" },
{ title: "Generated Photos", text: "Unique, worry-free model photos generated by AI", link: "https://generated.photos/" },
{ title: "UserStock", text: "Library for user avatars to use in your UI", link: "https://userstock.io/" },
{ title: "UI Faces", text: "Free avatar headshots that you can use in your design mockups", link: "https://uifaces.co/" },
{ title: "WOCinTech", text: "Free photos of women of color in tech", link: "https://www.flickr.com/photos/wocintechchat/" },
{ title: "Blush", text: "Illustrations for everyone", link: "https://blush.design/" },
{ title: "Drawkit", text: "Beautiful illustrations for you to use on your next website", link: "https://www.drawkit.io/" },
{ title: "Illlustrations", text: "A large set of open-source illustration library", link: "https://illlustrations.co/" },
{ title: "Ouch!", text: "Free vector illustrations to class up your project", link: "https://icons8.com/illustrations" },
{ title: "Lukaszadam", text: "Free graphical illustrations by an independent artist and designer", link: "https://lukaszadam.com/illustrations" },
{ title: "Vexels", text: "Free images and vector illustrations", link: "https://www.vexels.com/" },
{ title: "ManyPixeles", text: "Free images and vector illustrations", link: "https://www.manypixels.co/gallery" },
{ title: "Streamline", text: "Professional icons and illustrations", link: "https://streamlinehq.com/" },
{ title: "Humaaans", text: "Mix and match illustrations of people with a design library", link: "https://www.humaaans.com/" },
{ title: "Open Peeps", text: "A hand-drawn people illustration library", link: "https://www.openpeeps.com/" },
{ title: "Control", text: "108 customizable illustrations", link: "https://control.rocks/" },
{ title: "Absurd Design", text: "Absurd illustrations that make sense", link: "https://absurd.design/" },
{ title: "Fresh Folk", text: "An illustration library of mix and match people and objects", link: "https://fresh-folk.com/" },
{ title: "Open Doodles", text: "A free set of sketchy illustrations", link: "https://opendoodles.com/" },
{ title: "UnDraw", text: "Open-source illustrations for any idea", link: "https://undraw.co/illustrations" },
{ title: "Charco", text: "A set of 16 handcrafted illustrations", link: "https://www.karthiksrinivas.in/charco" },
{ title: "IRA Design", text: "Free editable illustration system", link: "https://iradesign.io/" },
{ title: "Avataaars", text: "Mix and match avatars illustration library", link: "https://avataaars.com/" },
{ title: "Personas", text: "A playful avatar generator for the modern age", link: "https://personas.draftbit.com/" },
{ title: "Dimensions", text: "A database of dimensioned drawings of everyday objects and spaces", link: "https://www.dimensions.com/" },
{ title: "Isometric Love", text: "Cute isometric objects for designers", link: "https://www.isometriclove.com/" },
{ title: "100 Food Illustrations", text: "100 Free Illustrations of food", link: "https://www.subscribepage.com/free-barcelonadesignshop-products" },
{ title: "404 Illustrations", text: "Royalty free illustrations for 404 pages", link: "https://error404.fun/" },
{ title: "Emojipedia", text: "Browse every emoji by name or platform", link: "https://emojipedia.org/" },
{ title: "Cursor.in", text: "SVG Mac cursor downloads", link: "http://cursor.in/" },
{ title: "Pattern Library", text: "Collection of pattern images", link: "http://thepatternlibrary.com/" },
{ title: "Pattern8", text: "Tons of funky, bold, and bright repeating patterns to choose from", link: "https://pattern8.com/" },
{ title: "Patternico", text: "Create your own patterns using Font Awesome icons", link: "https://patternico.com/" },
{ title: "Subtle Patterns", text: "Free downloadable patterns", link: "https://www.toptal.com/designers/subtlepatterns/" },
{ title: "Islamic Pattern Archive", text: "Free to use Islamic patterns", link: "https://patterninislamicart.com/" },
{ title: "Lost and Taken", text: "Free textures in a ton of categories", link: "https://lostandtaken.com/" },
{ title: "Get Waves", text: "Generate unique and organic SVG waves", link: "https://getwaves.io/" },
{ title: "Blobmaker", text: "Create organic svg shapes in just a few seconds", link: "https://www.blobmaker.app/" },
{ title: "Cool Backgrounds", text: "Generate minimal cool background for websites and blogs", link: "https://coolbackgrounds.io/" },
{ title: "Online Barcode Generator", text: "Easy to use barcode generator", link: "https://online-barcode-generator.net/" },
{ title: "Free Barcode Generator", text: "Comprehensive barcode generator", link: "https://www.free-barcode-generator.net/" },
{ title: "Snazzy Maps", text: "Google maps with custom color schemes", link: "https://snazzymaps.com/" },
{ title: "Stark", text: "Color-blind and contrast checker plugin for Figma, Adobe XD and Sketch", link: "https://www.getstark.co/" },
{ title: "Color Safe", text: "Build accessible color combinations", link: "http://colorsafe.co/" },
{ title: "Contrast for UI", text: "A macOS app for quick access to WCAG color contrast ratios", link: "https://usecontrast.com/" },
{ title: "Color Review", text: "A modern tool for exploring and finding accessible colors", link: "https://color.review/" },
{ title: "Colorable", text: "Test and use color combinations that are accessible", link: "https://colorable.jxnblk.com/" },
{ title: "Contrast Grid", text: "Test many color combinations for WCAG 2.0 compliance", link: "https://contrast-grid.eightshapes.com/" },
{ title: "Who can use", text: "Accessible color combination tester with different scenarios", link: "https://whocanuse.com/" },
{ title: "ColorBox", text: "Produce accessible color sets", link: "https://colorbox.io/" },
{ title: "Color Oracle", text: "Free color blindness simulator", link: "https://colororacle.org/" },
{ title: "Sim Daltonism", text: "Free color blindness simulator", link: "https://michelf.ca/projects/sim-daltonism/" },
{ title: "Accessible Brand Colors", text: "Create ADA compliant colors", link: "https://abc.useallfive.com/?ref=designresourc.es" },
{ title: "a11y Project", text: "Comunity-driven effort to make web accessibility easier", link: "https://www.a11yproject.com/" },
{ title: "Uplabs", text: "Free UI templates", link: "https://www.uplabs.com/" },
{ title: "Craftwork", text: "Free UI templates", link: "https://craftwork.design/" },
{ title: "Sketch App Sources", text: "Collection of free and premium Sketch resources", link: "https://www.sketchappsources.com/" },
{ title: "Figma Freebies", text: "A collection of design resources for the Figma community", link: "http://www.figmafreebi.es/" },
{ title: "UI8", text: "Curated digital marketplace for product designers", link: "https://ui8.net/" },
{ title: "Sketch Repo", text: "Discover Sketch resources for your next design project", link: "https://sketchrepo.com/" },
{ title: "UI bundle", text: "Discover free design assets from independent authors", link: "https://uibundle.com/" },
{ title: "DesignerMill", text: "Collection of free resources for designers", link: "https://www.designermill.com/" },
{ title: "Uplabs", text: "The best of design and development inspiration, resources and freebies", link: "https://www.uplabs.com/" },
{ title: "Freebie Supply", text: "Free, high quality design resources", link: "https://freebiesupply.com/" },
{ title: "iOS 13 UI kit", text: "Free collection of iOS 13 screens and components", link: "https://iosdesignkit.io/ios-13-gui/" },
{ title: "Speak Human", text: "Generate human centric microcopy for all purposes", link: "https://www.speakhuman.today/" },
{ title: "Hemingway App", text: "Text checker improving your writing for readability", link: "https://hemingwayapp.com/" },
{ title: "Nishi", text: "Curated collection of websites with good copywriting", link: "https://www.heynishi.com/" },
{ title: "Lorem Ipsum Generator", text: "Generate placeholder text", link: "https://loremipsum.io/" },
{ title: "Clippy", text: "Create custom CSS clips (masks) for your images", link: "https://bennettfeely.com/clippy/" },
{ title: "Effeckt", text: "A collection of CSS animation for elements", link: "https://h5bp.org/Effeckt.css/" },
{ title: "Zoomooz", text: "Zoom-in functionality for web sites", link: "http://jaukia.github.io/zoomooz/" },
{ title: "Smooth Shadow", text: "A smooth shadow generator", link: "https://shadows.brumm.af/" },
{ title: "Lottie", text: "Easily add high-quality animation to any native app", link: "https://airbnb.design/lottie/" },
{ title: "Animista", text: "CSS animation generator", link: "https://animista.net/" },
{ title: "Confusify", text: "Automatically switch font glyphs for unicode confusables", link: "https://github.com/NaN-xyz/Confusify" },
{ title: "3D Emoji Town", text: "An editable code for a 3D Emoji Town", link: "https://codepen.io/GeorgePark/pen/MqVoYP?fbclid=IwAR1ga9RiWDKExWmDQg3xrqRoy18YXqUU91MJJqCaepa9K2OHwXHC6AJLqhQ" },
{ title: "H5P", text: "A collection of interactive HTML5 content", link: "https://h5p.org/" },
{ title: "CodyHouse", text: "A collection of useful code snippets", link: "https://codyhouse.co/library" },
{ title: "Codrops", text: "A collection of useful code snippets", link: "https://tympanus.net/codrops/" },
{ title: "Grid", text: "A simple guide to responsive design", link: "https://adamkaplan.me/grid/" },
{ title: "Persona", text: "Creative and easy to use web builder", link: "https://persona.co/" },
{ title: "Fronty", text: "Image to website converter", link: "https://fronty.com/" },
{ title: "Fuge", text: "Royalty-Free music", link: "https://icons8.com/music/" },
{ title: "CChound", text: "100% free, quality CC audio", link: "https://cchound.com/" },
{ title: "HookSounds", text: "Get original royalty free music", link: "https://www.hooksounds.com/" },
{ title: "Groove Bakery", text: "Free music for all your projects", link: "https://groovebakery.com/" },
{ title: "Freesound", text: "Free to use sound effects", link: "https://freesound.org/" },
{ title: "Natural Readers", text: "Voice synthesiser", link: "https://www.naturalreaders.com/" },
{ title: "Acapela Group", text: "Voice synthesiser", link: "https://www.acapela-group.com/demos/" },
{ title: "Winter Company", text: "A collection of cover materials for packaging", link: "https://www.winter-company.com/en/product-selector/" },
{ title: "Foilco", text: "A collection of special foil materials", link: "https://www.foilco.com/foil-range/" },
{ title: "Templatemaker", text: "Paper box templates", link: "https://www.templatemaker.nl/en/" },
{ title: "Paper Sizes", text: "All the sizes for international paper formats", link: "https://papersizes.io/" },
{ title: "Pixlr- Online photo editor", text: "undefined", link: "https://pixlr.com/" },
{ title: "GIMP- Free & Open Source Image Editor", text: "undefined", link: "https://www.gimp.org/" },
{ title: "Smart Upscaler- Enlarge and enhance images automatically using AI", text: "undefined", link: "https://icons8.com/upscaler" },
{ title: "Remove Background", text: "Tool for removing image background easily", link: "https://www.remove.bg/" },
{ title: "Redacted", text: "Easily blur/pixelate/black out parts of an image", link: "https://redacted.app/" },
{ title: "TinyPNG", text: "Smart PNG and JPEG compression", link: "https://tinypng.com/" },
{ title: "Sumopaint", text: "Online image editor and drawing tool", link: "https://sumo.app/paint/en" },
{ title: "Overflow", text: "Turn your designs into playable user flow diagrams", link: "https://overflow.io/" },
{ title: "ProtoPie", text: "Interactive prototyping for digital products", link: "https://www.protopie.io/" },
{ title: "Shots", text: "Design responsive UI code based on hand-picked mobile design patterns", link: "https://www.shots.ai/" },
{ title: "Framer", text: "A powerful product that blends design and development", link: "https://www.framer.com/" },
{ title: "Principle", text: "Principle makes it easy to design animated and interacitve user interfaces", link: "https://principleformac.com/" },
{ title: "InVision Studio", text: "Turn screens into interactive prototypes", link: "https://www.invisionapp.com/" },
{ title: "Marvel", text: "Turn sketches, mockups and wireframes into interactive prototypes", link: "https://marvelapp.com/" },
{ title: "Flinto", text: "A mac app used to create interactive and animated app designs", link: "https://www.flinto.com/" },
{ title: "Voiceflow", text: "Design and prototyping tool for voice apps", link: "https://www.voiceflow.com/" },
{ title: "Proto.io", text: "Create fully-interactive high-fidelity prototypes", link: "https://proto.io/" },
{ title: "Bravo Studio", text: "Turn Figma and XD prototypes into native iOS and Android apps", link: "https://www.bravostudio.app/" },
{ title: "Phase", text: "Design and prototype websites and apps intuitively", link: "https://phase.com/" },
{ title: "Glide", text: "Build an app from Google Sheet", link: "https://www.glideapps.com/" },
{ title: "Maze", text: "Turn your prototype into actionable insights", link: "https://maze.co/" },
{ title: "DaVinci Resolve- Free video editing tool", text: "undefined", link: "https://www.blackmagicdesign.com/products/davinciresolve/" },
{ title: "VEED- Easy to use online video editor", text: "undefined", link: "https://www.veed.io/" },
{ title: "Unscreen- Remove video backgrounds 100% automatically", text: "undefined", link: "https://www.unscreen.com/" },
{ title: "MotionVFX", text: "A marketplace of premium and free video/motion resources", link: "https://www.motionvfx.com/" },
{ title: "Top Five AE Expressions", text: "A collection of useful copy-paste Adobe Aftereffects expressions", link: "https://www.graymachine.com/top-5-effects-expressions" },
{ title: "Processing", text: "Creative coding sofware", link: "https://processing.org/" },
{ title: "5.js", text: "Web based creative coding", link: "https://p5js.org/" },
{ title: "Mac Torrent Download", text: "Torrents for Mac native apps", link: "http://mac-torrent-download.net/" },
{ title: "Ninite", text: "Batch installer for multiple free to use programs", link: "https://ninite.com/" },
{ title: "BEE", text: "Design beautiful emails, fast", link: "https://beefree.io/" },
{ title: "Hoversignal", text: "A collection web growthacking widgets", link: "https://hoversignal.com/" },
{ title: "Kap", text: "An open-source screen recorder built with web technology", link: "https://getkap.co/" },
{ title: "World Vector Logo", text: "Largest SVG logo vector collection", link: "https://worldvectorlogo.com/" },
{ title: "How Big Is My Browser", text: "Find the size of your browser window", link: "http://howbigismybrowser.com/" },
{ title: "SocialSizes", text: "All image and video sizes for social media with templates", link: "https://socialsizes.io/" },
{ title: "Glyphy", text: "Copy and paste glyphs with ease", link: "https://www.glyphy.io/" },
{ title: "Extracting all URLs on a Web Page", text: "Extract all links from a web page inside Google Chrome", link: "https://towardsdatascience.com/quickly-extract-all-links-from-a-web-page-using-javascript-and-the-browser-console-49bb6f48127b" },
{ title: "Dummy Image", text: "Placeholder image generator with custom dimensions", link: "https://dummyimage.com/" },
{ title: "Design Systems", text: "An open-source checklist to help build design systems", link: "https://www.designsystemchecklist.com/" },
{ title: "Zeroheight", text: "Connect everyone working with your design system", link: "https://zeroheight.com/" },
{ title: "Design Systems", text: "A Figma publication for design systems", link: "https://www.designsystems.com/" },
{ title: "Catalog", text: "Design system inside a web template", link: "https://www.catalog.style/" },
{ title: "Design Lobby", text: "Manage design assets & version control", link: "https://designlobby.app/" },
{ title: "Done!", text: "An open source design system for everyone", link: "https://uilibrary.github.io/done-design-system/" },
{ title: "Modulator", text: "A quick and simple website styleguide generator", link: "https://hihayk.github.io/modulator/" },
{ title: "Fractal", text: "Web template for website styleguides", link: "https://fractal.build/" },
{ title: "Dimmy.club", text: "Device mockup generator for your screenshots", link: "https://dimmy.club/" },
{ title: "Shotsnapp", text: "Free device mockup presentation tool for your app and website design", link: "https://app.shotsnapp.com/" },
{ title: "Mockupmark", text: "Online T-shirt and apparel mockup generator", link: "https://mockupmark.com/" },
{ title: "Roatato", text: "Customizable 3D mockups generator", link: "https://www.rotato.app/" },
{ title: "Threed.io", text: "Browser based phone mockup generator", link: "https://threed.io/" },
{ title: "Artboard Studio", text: "Online graphic design app focused on product mockups", link: "https://artboard.studio/" },
{ title: "Overframe", text: "Record your prototype and app with device frame overlay", link: "https://overframe.xyz/" },
{ title: "Mockuuups Studio", text: "Generate 700+ drag and drop mockups", link: "https://mockuuups.studio/" },
{ title: "Store Previewer", text: "Preview your app on the App Store without the need for publishing it", link: "https://www.storepreviewer.com/" },
{ title: "Mock", text: "Create video mockups by adding a device frame to your videos", link: "https://www.mock.video/" },
{ title: "Screen Guru", text: "Take clean screenshots of any website", link: "https://screen.guru/" },
{ title: "Screenyl", text: "Instantly turn your screenshots into beautiful desktop mockups", link: "https://www.screely.com/" },
{ title: "Cleanmock", text: "Create mockups that make your design standout", link: "https://cleanmock.com/" },
{ title: "Animockup", text: "Animated product mockups with videos and animated GIFs", link: "https://animockup.com/" },
{ title: "Mckups", text: "Free photorealistic mockups", link: "https://mckups.com/" },
{ title: "The Mockup Club", text: "Showcasing great free mockups", link: "https://themockup.club/" },
{ title: "Facebook Devices", text: "Images and Sketch files of popular devices", link: "https://design.facebook.com/toolsandresources/devices" },
{ title: "Angle", text: "Vector and 3D device mockups", link: "https://angle.sh/" },
{ title: "Original Mockups", text: "Discover various free and premium mockups", link: "https://originalmockups.com/mockups/free-mockups" },
{ title: "Pixden", text: "Premium mockups", link: "https://www.pixeden.com/" },
{ title: "CSSauthor", text: "A collection of 2000+ free mockup templates", link: "https://cssauthor.com/free-mockup-templates-psd-designs/" },
{ title: "Paste", text: "Fast, collaborative presentations for creative teams", link: "https://paste.bywetransfer.com/" },
{ title: "Pitch", text: "Collaborative presentation sofware for modern teams", link: "https://pitch.com/" },
{ title: "Fermants Library", text: "Tools for academic writing", link: "https://fermatslibrary.com/" },
{ title: "Zotero", text: "Easy-to-use bibliography tool", link: "https://www.zotero.org/" },
{ title: "Design Dictionary", text: "A broad range of important terms you'll hear in your career as a designer", link: "https://www.figma.com/dictionary/" },
{ title: "Graphic Design Reading", text: "A collection of desgin articles", link: "https://readings.design/" },
{ title: "Webflow University", text: "Learn web design with free video courses and tutorials", link: "https://university.webflow.com/courses" },
{ title: "Laws of UX", text: "Researched principles and laws that help guide design process", link: "https://lawsofux.com/" },
{ title: "Growth Design", text: "Growth and UX case studies in a comic book format", link: "https://growth.design/case-studies/" },
{ title: "Apple Design Videos", text: "Learn about developing for Apple platforms with Apple experts", link: "https://developer.apple.com/videos/" },
{ title: "Humane", text: "Tips for designing ethically humane digital products", link: "https://humanebydesign.com/" },
{ title: "Design+Code", text: "Complete courses about the best tools and design systems", link: "https://designcode.io/" },
{ title: "Material Design", text: "Learn about creating intuitive and beautiful products with material design", link: "https://material.io/design" },
{ title: "Design Better", text: "The essential guide to the best design practices from top design experts ", link: "https://www.designbetter.co/" },
{ title: "IBM Design", text: "Learn about IBM's design philosophy", link: "https://www.ibm.com/design/practices/" },
{ title: "DesignerUp", text: "Learn how to design more mindful, impactful digital products", link: "https://designerup.co/" },
{ title: "Case Study Club", text: "Curated gallery of the best UI/UX design case studies", link: "https://www.casestudy.club/" },
{ title: "Apple HIG", text: "Designing iOS applications", link: "https://developer.apple.com/design/human-interface-guidelines/" },
{ title: "Nielsen Norman Group", text: "World leaders in research-based urser experience", link: "https://www.nngroup.com/" },
{ title: "Degreeless.design", text: "Everything from design school, without design school", link: "https://www.degreeless.design/" },
{ title: "Learn Mobile Design", text: "A currated list of mobile design resources", link: "https://learnmobile.design/" },
{ title: "Shortcuts.design", text: "All shortcuts for designers in one place", link: "https://shortcuts.design/" },
{ title: "Digital Psychology", text: "A free library of psychological principles and examples for inspiration", link: "https://digitalpsychology.io/" },
{ title: "Design Principles", text: "Open source collection of design principles and methods", link: "https://principles.design/" },
{ title: "Productdesign.tips", text: "Design knowledge and inspiration", link: "https://productdesign.tips/" },
{ title: "UX Starter Pack", text: "Comprehensive guide to landing your first UX job", link: "https://uxstarterpack.com/" },
{ title: "Briefbox", text: "Tutorials and creative inspiration for designers", link: "https://www.briefbox.me/" },
{ title: "Booklets.io", text: "Bite sized learning for creatives", link: "https://www.booklets.io/" },
{ title: "UX Myths", text: "Build your product based on evidence, not false beliefs", link: "https://uxmyths.com/" },
{ title: "Lapa Learn", text: "Landing page design inspiration from around the web", link: "https://www.lapa.ninja/learn/" },
{ title: "LearnUX.io", text: "A complete approach to learning UI/UX tools", link: "https://learnux.io/" },
{ title: "Designers.watch", text: "The best documentaries for designers and artists", link: "https://designers.watch/" },
{ title: "Sketch Together", text: "All things related to user experience and user interface design", link: "https://www.youtube.com/c/SketchTogetherTV/videos" },
{ title: "Intro to Icons", text: "Learn the fundamentals of icon design", link: "http://introtoicons.com/" },
{ title: "CharliMarieTV", text: "Graphic designers from New Zealand showing projects, conceptc and vlogs", link: "https://www.youtube.com/c/charlimarieTV/videos" },
{ title: "Dann Petty", text: "Web designer and author", link: "https://www.youtube.com/user/dannpetty/videos" },
{ title: "Flux", text: "Flux is the personal vlog of Ran Segall, a designer and entrepreneur", link: "https://www.youtube.com/c/FluxWithRanSegall/videos" },
{ title: "Femke", text: "Product designer focusing on learnings and experiences of being a designer", link: "https://www.youtube.com/c/femkedesign/videos" },
{ title: "Internet Archive", text: "An enormous archive of books, websites and much more", link: "https://archive.org/" },
{ title: "Design Better Podcast", text: "Insights from the world's most renowned design leaders", link: "https://www.designbetter.co/podcast" },
{ title: "Roots", text: "A weekly podcasts profiling the stories of Filipino designers", link: "https://rootspodcast.design/" },
{ title: "New Layer", text: "A conversation on everything related to digital product design", link: "https://anchor.fm/new-layer" },
{ title: "Design Life", text: "Two women in tech talk about balancing side projects on top of a full time job ", link: "https://www.designlife.fm/" },
{ title: "Design Details", text: "A weekly conversation about design process and culture", link: "https://designdetails.fm/episodes" },
{ title: "Yo!", text: "Yo! is a celebration of great design and development online", link: "https://robhope.com/yo" },
{ title: "Opacity", text: "A podcast about working in design", link: "https://anchor.fm/opacity" },
{ title: "Whiteboard.fm", text: "A designers interview series focusing on internships and job experiences", link: "https://anchor.fm/whiteboardfm" },
{ title: "Design Matters", text: "Podcast about design and creative culture", link: "https://www.designmattersmedia.com/designmatters" },
{ title: "Design Notes", text: "Get design inspiration and insights from Google", link: "https://design.google/library/podcasts/" },
{ title: "Inside Intercom", text: "Interviews from makers from the worlds of product design and startups", link: "https://www.intercom.com/blog/podcasts" },
{ title: "Designed Today", text: "Improve your design, branding, marketing, and advertising skills in one place", link: "https://pod.link/designedtoday" },
{ title: "Product Hunt Radio", text: "A weekly podcast with the people creating and exploring the future", link: "https://www.producthunt.com/radio" },
{ title: "Overtime", text: "Dribbbles's official podcast goes behind the shots of your favorite designers", link: "https://dribbble.com/overtime" },
{ title: "Presentable", text: "How we design and build the products that are shaping our digital future", link: "https://www.relay.fm/presentable" },
{ title: "Layout", text: "Weekly podcast about design, tech, programming and everything else", link: "https://layout.fm/" },
{ title: "Panda", text: "Keep up to date with design and news sources", link: "https://usepanda.com/" },
{ title: "Hey Designer", text: "Daily curated newsfeed for UXers, PMs and frontend developers", link: "https://heydesigner.com/" },
{ title: "Sidebar", text: "The five best design links, every day", link: "https://sidebar.io/" },
{ title: "Design Calendar", text: "The best onine design events", link: "https://www.designcalendar.io/remote/events" },
{ title: "UX Collective", text: "Curated stories on UX, Visual and Product Design", link: "https://uxdesign.cc/" },
{ title: "Product Hunt", text: "A curation of the best new products, every day", link: "https://www.producthunt.com/" },
{ title: "Google Design", text: "Writings of designers, writers, and developers at Google", link: "https://design.google/" },
{ title: "Facebook Design", text: "A collection of tools and resources from Facebook Design", link: "https://design.facebook.com/" },
{ title: "Microsoft Design", text: "Latest news from Microsoft design", link: "https://www.microsoft.com/design/" },
{ title: "Dropbox Design", text: "A collection of resources from Dropbox design team", link: "https://dropbox.design/" },
{ title: "Airbnb Design", text: "Behind the scenes of Airbnb's creative culture through the lens of our team", link: "https://airbnb.design/" },
{ title: "Designer News", text: "A community for designers to share interesting links and events", link: "https://www.designernews.co/" },
{ title: "UX Design Weekly", text: "Hand picked list of the best user experience design links", link: "https://uxdesignweekly.com/" },
{ title: "Medium", text: "Follow to get great stories about Design on Medium", link: "https://medium.com/topic/design" },
{ title: "Inside Design", text: "A new online resource for all things digital product design. Created by InVision", link: "https://www.invisionapp.com/inside-design/" },
{ title: "BetaList", text: "A community of makers showcasing their startups and exchanging feedback", link: "https://betalist.com/" },
{ title: "Lovers Magazine", text: "An online magazine for creative professionals", link: "https://www.loversmagazine.com/" },
{ title: "The DESK Magazine", text: "An online magazine exploring design, psychology and productivity", link: "https://vanschneider.com/blog/" },
{ title: "Prototypr", text: "The best design news, handpicked every day", link: "https://prototypr.io/" },
{ title: "Figmailon", text: "Curated newsletter collecting interesting links about Figma", link: "https://figmalion.com/" },
{ title: "Fragments", text: "Repository of news for design, development and art", link: "https://fragments.pro/" },
{ title: "Women Who Design", text: "Directory of accomplished women in the design industry", link: "https://womenwho.design/" },
{ title: "Web Designer News", text: "A curated collection of the best news for designers each day", link: "https://www.webdesignernews.com/" },
{ title: "Designmodo", text: "Web design articles, tutorials and more", link: "https://designmodo.com/articles/" },
{ title: "UX Movement", text: "Learn new and innovative best practices in user experience design", link: "https://uxmovement.com/" },
{ title: "Ustwo.blog", text: "Digital products, services and companies. We learn through making.", link: "https://www.ustwo.com/blog/" },
{ title: "Another Design", text: "Design email newsletter from Pablo Stanley", link: "https://www.anotherdesignnewsletter.com/" },
{ title: "All Design Conferences", text: "Simple collection of all design and front-end conferences", link: "https://www.alldesignconferences.com/" },
]
